name: quarterly-scrape
on:
  schedule:
    - cron: '0 14 15 2,5,8,11 *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest

    # 👇 NEW: make secrets.SEC_EMAIL visible as $SEC_EMAIL
    env:
      SEC_EMAIL: ${{ secrets.SEC_EMAIL }}
      SEC_COMPANY: ${{ secrets.SEC_COMPANY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scrape.py

      - name: Commit data file
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add holdings.parquet
          git commit -m "Auto-update data" || echo "Nothing to commit"
          git push
